title: Greativity
email: hanafiah.ramadhan@gmail.com
description: > 
  I'm a newcomer who learn and forget, and made it documented as much as possible. Work for eternity.
baseurl: ""
url: ""
twitter_username: rama_than
github_username:  ramadhinov
ig_username: psychocode
fb_username: ramadhinolfski
in_username: lutfi-ramadhan-2b74586a
markdown: kramdown